#!/usr/bin/env bash

set -e

cd "$(dirname "$0")"

source config

echo "Checking Isabelle ..."
if [ -x "$ISABELLE_TOOL" ]; then
  echo "Isabelle present at $ISABELLE_TOOL"
else
  echo "Isabelle not present. Set \$ISABELLE_TOOL in config."
  exit 1
fi

echo "Checking AFP ..."
if [ -d "$AFP" ]; then
  echo "AFP present at $AFP"
  AFP_STRING=("-d" "$AFP")
else
  echo "AFP not present. Either set \$AFP in config, or make sure that the AFP is otherwise registered as session root."
  AFP_STRING=("")
fi

if [ ! -f lem.zip ]; then
  echo "Downloading Lem ..."
  curl -sLo lem.zip "$LEM_REPOSITORY/archive/$LEM_COMMIT.zip"
fi

if [ ! -f cakeml.zip ]; then
  echo "Downloading CakeML ..."
  curl -sLo cakeml.zip "$CAKEML_REPOSITORY/archive/$CAKEML_COMMIT.zip"
fi

RAW_TARGET="download"
TARGET="thy"
GENERATED_TARGET="$TARGET/generated"

echo "Cleaning ..."
rm -rf "$RAW_TARGET"
mkdir -p "$RAW_TARGET"
rm -rf "$GENERATED_TARGET"
mkdir -p "$GENERATED_TARGET"

echo "Unpacking Lem ..."
unzip -oq lem.zip -d "$RAW_TARGET"

echo "Unpacking CakeML ..."
unzip -oq cakeml.zip -d "$RAW_TARGET"

LEM_RAW_TARGET="download/lem-$LEM_COMMIT"
CAKEML_RAW_TARGET="download/cakeml-$CAKEML_COMMIT"

echo "Checking download ..."
if [ ! -d "$LEM_RAW_TARGET" ] || [ ! -d "$CAKEML_RAW_TARGET" ]; then
  echo "Outdated download, clean and try again"
  exit 1
fi

echo "Making Lem ..."
make -C "$LEM_RAW_TARGET" bin/lem

echo "Generating Lem/Isabelle libraries ..."
make -C "$LEM_RAW_TARGET/library"

echo "Checking Lem ..."
LEM_BINARY="$LEM_RAW_TARGET/bin/lem"
if [ ! -x "$LEM_BINARY" ]; then
  echo "Failed to produce Lem binary"
  exit 1
fi

echo "Copying Lem/Isabelle theories ..."
cp "$LEM_RAW_TARGET/isabelle-lib/"*.thy "$GENERATED_TARGET"

echo "Generating CakeML/Isabelle theories ..."
(
  LEM_BINARY="$(readlink -f "$LEM_BINARY")"
  GENERATED_TARGET="$(readlink -f "$GENERATED_TARGET")/CakeML"
  cd "$CAKEML_RAW_TARGET"
  mkdir -p "$GENERATED_TARGET"
  "$LEM_BINARY" -isa -outdir "$GENERATED_TARGET" "${CAKEML_LEM_FILES[@]}"
)

echo "Patching theories ..."
find "$GENERATED_TARGET/CakeML" -name "*.thy" -exec sed -i -e 's/"Lem/"LEM.Lem/' {} \;

echo "Building theories ..."
"$ISABELLE_TOOL" build -v "${AFP_STRING[@]}" -D "$TARGET"
