#!/usr/bin/env bash

set -e

cd "$(dirname "$0")"

echo "Checking that the working directory is clean ..."
git diff --exit-code > /dev/null
git diff --cached --exit-code > /dev/null

echo "Creating archive ..."
REV="$(git rev-parse --short HEAD)"
git archive --format=zip -o "afp-$REV.zip" --prefix=CakeML/ HEAD:thy

echo "Success: afp-$REV.zip."
