#!/usr/bin/env bash

set -e

cd "$(dirname "$0")"

source setup

echo "Checking cleanliness of AFP ..."

( hg -R "$AFP/.." summary | grep -q 'commit: (clean)' ) || (
  echo "AFP not clean"
  exit 1
)

echo "AFP clean"

echo "Checking that the working directory is clean ..."
git diff --exit-code > /dev/null
git diff --cached --exit-code > /dev/null

echo "Working directory is clean"

echo "Transferring files from AFP ..."

rm -rf "thy"
TEMP="$(mktemp -d)"
hg -R "$AFP/.." archive -t files "$TEMP"
cp -r "$TEMP/thys/CakeML" "thy"

echo "Success."
